### ISSUE TITLE
State is not shared across ProcessPoolExecutor

### ISSUE THREAD

**Issue by denyszhak** [jamesls/fakeredis#327]
I went through the limitations of transactions in fakeredis and stuff, but to double-check if haven't missed anything.
Fakeredis is not an option to test different processes accessing the same resource?
redis-py throws WatchError since no response, fakeredis doesn't

```python
"""
fakeredis vs redis transaction with watch
"""
from concurrent.futures import ProcessPoolExecutor

from fakeredis import FakeRedis
from redis import Redis, WatchError


def watch_update() -> None:
    client = Redis()

    with client.pipeline() as pipe:
        pipe.watch("key")
        pipe.multi()
        pipe.set("key", "value")

        try:
            pipe.execute()
        except WatchError as exc:
            print(exc)


def test_watch_update() -> None:
    with ProcessPoolExecutor(max_workers=4) as executor:
        for task in range(2):
            print(f"task {task}")
            executor.submit(watch_update)


if __name__ == "__main__":
    test_watch_update()
```

**Comment by bmerry** [comment]
fakeredis keeps all the state inside a process rather than having a separate server. So if you run multiple processes they'll each have their own state, just like if you were storing data in a dictionary. If you're already dealing with multiple processes, you might want to just spin up an actual redis server (possibly [redislite](https://redislite.readthedocs.io/en/latest/) could help here, but I've never looked into it so I don't know).

**Comment by denyszhak** [comment]
@bmerry 
lol, that make sense, thanks
