### ISSUE TITLE
fakeredis should support `execute_command` method

### ISSUE THREAD

**Issue by lfyzjck** [jamesls/fakeredis#65]
In some cases, people may use redis.Redis.execute_command directly

**Comment by sazlin** [comment]
+1

**Comment by ccp-codex** [comment]
+1

**Comment by anderson-dan-w** [comment]
Any update on this? Any reason it's not one of the commands listed as "unimplemented" in the documentation?

**Comment by anderson-dan-w** [comment]
Issue with the code snippet above is that `redispy` has limited functionality with certain calls, eg `zadd`: as it currently exists, can't use `xx` or `nx` flags directly in `zadd` calls.

So, my solution was to monkeypatch `zadd` to call `execute_command()` with something like [this suggestion](https://github.com/andymccurdy/redis-py/issues/649#issuecomment-350199603). This works in `redispy`, but wouldn't work in the above snippet because it would just call the already-lacking `zadd`.

**Comment by bmerry** [comment]
`execute_command` is fully supported in 1.0rc1, so I'm going to close this.

Unfortunately your specific use case (`zadd` with `xx`/`nx`) still isn't implemented, but it shouldn't be too hard to implement. Pull requests welcome.
